### ISSUE TITLE
Uncaught ReferenceError when clicking CSS Dig icon.

### ISSUE THREAD

**Issue by patrickbard** [tomgenoni/cssdig-chrome#12]
I've just installed CSS Dig and got an error when I click on the icon.

Here is what the console shows:

![Error Image](http://i.xomf.com/bwbnf.png)

(Running on Chrome 55.0.2883.87)

**Comment by tomgenoni** [comment]
Could you tell me the URL where you're seeing this happen? Does it happen on other websites?
